#!/bin/bash

# Constants
DESTINATION="/usr/local/bin"

# Function to check if an argument is provided
checkArgument() {
    if [ -z "$1" ]; then
        echo "Usage: $0 <file>"
        exit 1
    fi
}

# Function to check if the file exists
checkFileExistence() {
    if [ ! -f "$1" ]; then
        echo "Error: File not found."
        exit 1
    fi
}

# Function to give executable permission
makeExecutable() {
    chmod +x "$1"
    if [ $? -ne 0 ]; then
        echo "Error: Unable to make $1 executable."
        exit 1
    fi
    echo "File $1 is now executable."
}

# Function to copy the file to the specified directory
copyToBin() {
    local filename=$(basename "$1")
    sudo cp "$1" "$2/$filename"
    if [ $? -ne 0 ]; then
        echo "Error: Unable to copy $1 to $2."
        exit 1
    fi
    echo "File $1 is now in $2."
}

# Main script

# Check if an argument is provided
checkArgument "$1"

# Check if the file exists
checkFileExistence "$1"

# Give executable permission
makeExecutable "$1"

# Copy the file to the specified directory
copyToBin "$1" "$DESTINATION"
